name: Snyk .NET dependencies
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk-deps.sarif --file=DevOpsDotnet.sln --include-ignores
          command: "test"
      - name: Upload result to GitHub Code Scanning
        if: ${{ hashFiles('snyk-deps') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-deps
          category: snyk-dependencies
