name: Stryker mutator (mutation tests)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Set branches
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; \
            then
              echo "Target branch is $PR_BASE_REF"
              echo "Source branch is $PR_REF"
              echo "TARGET_BRANCH=$PR_BASE_REF" >> $GITHUB_ENV
              echo "SOURCE_BRANCH=$PR_REF" >> $GITHUB_ENV
            else
              echo "Target branch is $DEFAULT_BRANCH"
              echo "TARGET_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
              echo "Source branch is $REF_NAME"
              echo "SOURCE_BRANCH=$REF_NAME" >> $GITHUB_ENV
            fi
        env:
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_REF: ${{ github.ref }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          REF_NAME: ${{ github.ref_name }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all branches
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Install Stryker.NET
        run: dotnet tool install --global dotnet-stryker

      - name: Run Stryker (dashboard)
        run: |
          dotnet tool restore
          dotnet stryker -f .config/stryker-config.json --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version ${{ env.SOURCE_BRANCH }} --reporter dashboard

      - name: Run Stryker (html)
        run: |
          dotnet tool restore
          dotnet stryker -f .config/stryker-config.json --reporter html

      - name: Upload Stryker Report
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: ${{github.workspace}}/StrykerOutput/**/**/*.html

      - name: Report message
        uses: mshick/add-pr-comment@v2
        with:
          update-only: true
          message: |
            <img src="https://devopsjournal.io/images/2019/20191004/20191004_Stryker_Logo.png" width="100" /> <br />
            Stryker dashboard : [here](https://dashboard.stryker-mutator.io/reports/github.com/kurnakovv/DevOpsDotnet/${{ github.ref }}#mutant) <br />
            [![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https://badge-api.stryker-mutator.io/github.com/kurnakovv/DevOpsDotnet/${{ github.ref }})](https://dashboard.stryker-mutator.io/reports/github.com/kurnakovv/DevOpsDotnet/${{ github.ref }}#mutant) <br/>
            Download html report: ${{ steps.artifact-upload-step.outputs.artifact-url }}
