name: Stryker mutator (mutation tests)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mutation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Install Stryker.NET
        run: dotnet tool install --global dotnet-stryker

      - name: Add Stryker to PATH
        run: echo "${{ github.env.GITHUB_ENV }}" >> $HOME/.bashrc

      - name: Run Stryker
        run: dotnet stryker