# name: Stryker mutator (mutation tests)

# on:
#   push:
#     branches:
#       - '*'
#   pull_request:
#     types: [opened, synchronize, reopened]

# jobs:
#   mutation-test:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write
#     steps:
#       - name: Set global variables
#         run: |
#           if [[ "${{ github.event_name }}" == "pull_request" ]]; \
#           then
#             echo "This is a pull request"

#             echo "Target branch is $PR_BASE_REF"
#             echo "TARGET_BRANCH=$PR_BASE_REF" >> $GITHUB_ENV

#             echo "Source branch is $PR_REF"
#             echo "SOURCE_BRANCH=$PR_REF" >> $GITHUB_ENV
#           else
#             echo "This is not a pull request"

#             if [[ "$REF_NAME" != "$DEFAULT_BRANCH" ]]; \
#             then
#               echo "Current branch is not a default branch ($REF_NAME != $DEFAULT_BRANCH)"

#               echo "Target branch is $DEFAULT_BRANCH"
#               echo "TARGET_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
#             else
#               echo "Current branch is default ($REF_NAME == $DEFAULT_BRANCH)"
#             fi

#             echo "Source branch is $REF_NAME"
#             echo "SOURCE_BRANCH=$REF_NAME" >> $GITHUB_ENV
#           fi

#           echo "Config path is $CONFIG_PATH"
#           echo "CONFIG_PATH=$CONFIG_PATH" >> $GITHUB_ENV
#         env:
#           PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
#           PR_REF: ${{ github.ref }}
#           DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
#           REF_NAME: ${{ github.ref_name }}
#           CONFIG_PATH: ".config/stryker-config.json"

#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # fetch all branches
      
#       - name: Setup .NET
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: 9.0.x

#       - name: Install dependencies
#         run: dotnet restore

#       - name: Install Stryker.NET
#         run: |
#           dotnet tool install --global dotnet-stryker
#           dotnet tool restore

#       - name: Run Stryker (diff)
#         run: |
#           dotnet stryker -f ${{ env.CONFIG_PATH }} --since:${{ env.TARGET_BRANCH }} --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version ${{ env.SOURCE_BRANCH }}-diff --reporter dashboard --reporter html --output StrykerOutputDiff
#         if: github.ref_name != github.event.repository.default_branch

#       - name: Run Stryker (source branch)
#         run: |
#           dotnet stryker -f ${{ env.CONFIG_PATH }} --dashboard-api-key ${{ secrets.STRYKER_DASHBOARD_API_KEY }} --version ${{ env.SOURCE_BRANCH }} --reporter dashboard --reporter html --output StrykerOutput

#       - name: Upload Stryker Report
#         id: artifact-upload-step
#         uses: actions/upload-artifact@v4
#         with:
#           name: stryker-report
#           path: |
#             ${{github.workspace}}/StrykerOutputDiff/**/**/*.html
#             ${{github.workspace}}/StrykerOutput/**/**/*.html

#       - name: Report message
#         uses: mshick/add-pr-comment@v2
#         with:
#           message: |
#             <img src="https://devopsjournal.io/images/2019/20191004/20191004_Stryker_Logo.png" width="100" />

#             # Stryker .NET

#             | Description  | Badge |
#             | ------------ | ----- |
#             | Diff between `${{ env.TARGET_BRANCH }}` (target branch) and `${{ env.SOURCE_BRANCH }}` (source branch) | [![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https://badge-api.stryker-mutator.io/github.com/kurnakovv/DevOpsDotnet/${{ env.SOURCE_BRANCH }}-diff)](https://dashboard.stryker-mutator.io/reports/github.com/kurnakovv/DevOpsDotnet/${{ env.SOURCE_BRANCH }}-diff#mutant) |
#             | `${{ env.SOURCE_BRANCH }}` (source branch) statistics | [![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https://badge-api.stryker-mutator.io/github.com/kurnakovv/DevOpsDotnet/${{ env.SOURCE_BRANCH }})](https://dashboard.stryker-mutator.io/reports/github.com/kurnakovv/DevOpsDotnet/${{ env.SOURCE_BRANCH }}#mutant) |
#             | `${{ env.TARGET_BRANCH }}` (target branch) statistics | [![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https://badge-api.stryker-mutator.io/github.com/kurnakovv/DevOpsDotnet/${{ env.TARGET_BRANCH }})](https://dashboard.stryker-mutator.io/reports/github.com/kurnakovv/DevOpsDotnet/${{ env.TARGET_BRANCH }}#mutant) |

#             Download report: ${{ steps.artifact-upload-step.outputs.artifact-url }}
#         if: github.event_name == 'pull_request'
